# Generated by Django 4.2.1 on 2023-06-16 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_user', '0002_alert_alertprivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSplitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('camera_name', models.CharField(blank=True, max_length=180, null=True)),
                ('x_start', models.FloatField(default=0)),
                ('x_end', models.FloatField(default=1)),
                ('y_start', models.FloatField(default=0)),
                ('y_end', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraSplitSettingPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('camera_name', models.CharField(blank=True, max_length=180, null=True)),
                ('x_start', models.FloatField(default=0)),
                ('x_end', models.FloatField(default=1)),
                ('y_start', models.FloatField(default=0)),
                ('y_end', models.FloatField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
