# Generated by Django 4.2.1 on 2023-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_camerasplitsetting_camerasplitsettingprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasplitsetting',
            name='is_original_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camerasplitsettingprivate',
            name='is_original_state',
            field=models.BooleanField(default=True),
        ),
    ]
