# Generated by Django 4.2.1 on 2023-06-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_rename_folder_code_alert_alert_folder_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertprivate',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
