# Generated by Django 4.2.1 on 2023-06-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_alert_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_one_item',
            field=models.CharField(choices=[('none', 'none'), ('image', 'image'), ('video', 'video'), ('folder', 'folder')], default='none', max_length=180),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_two_item',
            field=models.CharField(choices=[('none', 'none'), ('image', 'image'), ('video', 'video'), ('folder', 'folder')], default='none', max_length=180),
        ),
        migrations.AddField(
            model_name='alertprivate',
            name='last_one_item',
            field=models.CharField(choices=[('none', 'none'), ('image', 'image'), ('video', 'video'), ('folder', 'folder')], default='none', max_length=180),
        ),
        migrations.AddField(
            model_name='alertprivate',
            name='last_two_item',
            field=models.CharField(choices=[('none', 'none'), ('image', 'image'), ('video', 'video'), ('folder', 'folder')], default='none', max_length=180),
        ),
    ]
