# Generated by Django 4.2.1 on 2023-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0014_alert_alert_pure_code_alert_alert_pure_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_pure_camera_setting_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_pure_password_change_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_pure_profile_setting_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertprivate',
            name='alert_pure_camera_setting_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertprivate',
            name='alert_pure_password_change_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertprivate',
            name='alert_pure_profile_setting_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
