# Generated by Django 4.2.1 on 2023-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0015_alert_alert_pure_camera_setting_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_pure_quantity',
        ),
        migrations.RemoveField(
            model_name='alertprivate',
            name='alert_pure_quantity',
        ),
    ]
