# Generated by Django 4.2.1 on 2023-05-22 09:00

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_imagemultiplefolder_alter_imageprivate_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
