# Generated by Django 4.2.1 on 2023-06-05 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0004_alter_imageprivate_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.CreateModel(
            name='ImageMultipleFolderPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('image_file', models.ImageField(upload_to=image.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
