# Generated by Django 4.2.1 on 2023-06-20 08:20

from django.conf import settings
from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0016_rename_imagealertprivate_imagealertnormaluser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageAlert',
            new_name='AlertImage',
        ),
        migrations.RenameModel(
            old_name='ImageMultipleFolderAlert',
            new_name='AlertImageMultipleFolder',
        ),
        migrations.RenameModel(
            old_name='ImageMultipleFolderAlertPrivate',
            new_name='AlertImageMultipleFolderPrivate',
        ),
        migrations.RenameModel(
            old_name='ImageAlertNormalUser',
            new_name='AlertImageNormalUser',
        ),
        migrations.RenameModel(
            old_name='ImageAlertSuperUser',
            new_name='AlertImageSuperUser',
        ),
        migrations.AlterField(
            model_name='imagemultiplefolder',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
