# Generated by Django 4.2.1 on 2023-06-21 06:30

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0022_alter_imagemultiplefolder_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertimagemultiplefolder',
            name='folder_code',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alertimagemultiplefolderprivate',
            name='folder_code',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagemultiplefolder',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
