# Generated by Django 4.2.1 on 2023-06-21 07:12

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0026_alter_imagemultiplefolder_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_user',
            field=models.CharField(choices=[('guest', 'guest'), ('superuser', 'superuser')], default='guest', max_length=180),
        ),
        migrations.AlterField(
            model_name='imagemultiplefolder',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
