# Generated by Django 4.2.1 on 2023-06-21 07:22

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0027_image_created_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='imagemultiplefolder',
            name='user',
            field=models.CharField(choices=[('guest', 'guest'), ('superuser', 'superuser')], default='guest', max_length=180),
        ),
        migrations.AlterField(
            model_name='imagemultiplefolder',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
