# Generated by Django 4.2.1 on 2023-06-28 01:25

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0035_alter_alertimagesuperuser_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertimagesuperuser',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='imagemultiplefolder',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
