# Generated by Django 4.2.1 on 2023-06-28 02:36

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0039_alter_imagemultiplefolder_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertimagemultiplefolderprivate',
            name='delete_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertimagemultiplefolderprivate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagemultiplefolder',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageprivate',
            name='image_file',
            field=models.ImageField(upload_to=image.models.upload_to),
        ),
    ]
