# Generated by Django 4.2.1 on 2023-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alertvideosuperuser_alertvideonormaluser_alertvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videooutput',
            name='user',
            field=models.CharField(choices=[('guest', 'guest'), ('superuser', 'superuser')], default='guest', max_length=180),
        ),
    ]
