# Generated by Django 4.2.1 on 2023-06-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videooutput_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertvideo',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.videooutput'),
        ),
        migrations.AlterField(
            model_name='alertvideonormaluser',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.videooutputprivate'),
        ),
        migrations.AlterField(
            model_name='alertvideosuperuser',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.videooutput'),
        ),
    ]
