# Generated by Django 4.2.1 on 2023-06-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alertvideosuperuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertvideo',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='alertvideonormaluser',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
