# Generated by Django 4.2.1 on 2023-07-13 03:54

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alertvideo_name_alertvideonormaluser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('videofile', models.FileField(upload_to=video.models.upload_to)),
            ],
        ),
    ]
